export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGOUT = 'USER_LOGOUT'

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const CONTACTS_LOAD_SUCCESS = "CONTACTS_LOAD_SUCCESS";
export const CONTACTS_LOAD_ERROR = "CONTACTS_LOAD_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
